# Generated by Django 4.0.4 on 2022-05-20 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_hotel_discription_hotels_hotel_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotels',
            name='hotel_image',
            field=models.CharField(max_length=500),
        ),
    ]
